{% set name = "pymeshlab" %}
{% set version = "2025.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/cnr-isti-vclab/PyMeshLab/archive/v{{ version }}.tar.gz
    sha256: f915318995bb4e0a4b1506d2d79e2f9ab543b836218982ff6c6e8f8127d7ac2d
  - url: https://github.com/cnr-isti-vclab/meshlab/archive/dc48b91ae562756a6988048c5d5c7f1d2b687256.tar.gz
    sha256: bac9cc42614ab5318f4c571a6d28eac7c1bfde69b601f9781d3e118d5a054da0
    folder: src/meshlab
  - url: https://github.com/cnr-isti-vclab/vcglib/archive/c94ef4e12e9ea3ae986d9af91005be8328d13719.tar.gz
    sha256: 346ff5386be9454fc6b70552d6e397c3d82efd3f8097bf06704c7a44ba3296d5
    folder: src/meshlab/src/vcglib
  - url: https://github.com/pybind/pybind11/archive/refs/tags/v2.13.6.tar.gz
    sha256: e08cb87f4773da97fa7b5f035de8763abc656d87d5773e62f6da0587d1f0ec20
    folder: src/pymeshlab/pybind11

build:
  number: 1
  missing_dso_whitelist:
    - '*/external-glew.dll'    # [win]
    - '*/external-lib3ds.dll'  # [win]
    - '*/IDTF.dll'             # [win]
    - '*/meshlab-common.dll'   # [win]
    - '$RPATH/lib3mf.so.2'     # [unix]
    - '*/lib3mf.dll'           # [win]
  skip: true  # [win and py>310]

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake <4
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make
    - ninja
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - python                                 # [build_platform != target_platform]
    - rsync        # [unix]
  host:
    - cgal
    - eigen
    - embree
    - glew
    - gmp
    - igl          # [linux64 or (osx and x86_64)]
    - lib3mf
    - libboost-devel
    - libcurl
    - libgl-devel  # [linux]
    - libglu       # [linux]
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - mpfr
    - muparser
    - nexus
    - qhull
    - pip
    - python
    - qt-main
    - setuptools
    - tbb-devel
    - tinygltf
    - u3d      # [win]
    - wheel
    - xerces-c
  run:
    - numpy
    - lib3mf
    - libglu   # [linux]
    - python
    - qt-main  # [win]
    - tbb      # [win]
    - u3d      # [win]

test:
  imports:
    - pymeshlab
  commands:
    - pip list
    # The 'pip check' command is disabled on Windows because it gives a false
    # negative due to a metadata mismatch (conda 'vc' vs pip 'msvc-runtime').
    # The 'imports' test above is the reliable indicator of a working package.
    - pip check  # [not win]
  requires:
    - pip
    - python

about:
  home: https://github.com/cnr-isti-vclab/PyMeshLab
  summary: The open source mesh processing python library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
