{% set name = "pymeshlab" %}
{% set version = "2023.12.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/cnr-isti-vclab/PyMeshLab/archive/v{{ version }}.tar.gz
    sha256: f7542489eec3545a0e0478795b5f01a9f204272ca44c9b94ca9f9290acd1bd6c
  - url: https://github.com/cnr-isti-vclab/meshlab/archive/2dbd2f4b12df3b47d8777b2b4a43cabd9e425735.tar.gz
    sha256: 9236ad0d27e6712be247148789737598058c8f332e0333a36f48c54d0a475061
    folder: src/meshlab
  - url: https://github.com/cnr-isti-vclab/vcglib/archive/6ac9e0c647a63e0e037813a1e92bd050d13efc85.tar.gz
    sha256: aeb76137d29f1c7f19b1d82b57e4f347139d3d345533c35578f944af83eea29d
    folder: src/meshlab/src/vcglib
  - url: https://github.com/pybind/pybind11/archive/refs/tags/v2.11.2.tar.gz
    sha256: c38f52f75a4e2af9a5bcff2368713101585acc06963891af5f03eaa7f4c04242
    folder: src/pymeshlab/pybind11

build:
  number: 2
  missing_dso_whitelist:
    - '*/meshlab-common.dll'  # [win]
    - '*/external-glew.dll'   # [win]
  skip: true  # [win and py>310]  # nothing provides vc 10 needed by boost-cpp-1.63.0-vc10_0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake <4
    - make
    - ninja
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - rsync        # [unix]
  host:
    - cgal
    - eigen
    - glew
    - gmp
    - icu
    - igl
    - libboost-devel
    - libcurl
    - libgl-devel  # [linux]
    - libglu       # [linux]
    - libgomp      # [linux]
    - libjpeg-turbo 2
    - llvm-openmp  # [osx]
    - mpfr
    - muparser
    - nexus
    - qhull
    - pip
    - python
    - qt-main
    - setuptools
    - tinygltf
    - u3d
    - wheel
  run:
    - qt-main  # [win]
    - numpy
    - libglu  # [linux]
    - python

test:
  imports:
    - pymeshlab
  commands:
    - pip list
    # The 'pip check' command is disabled on Windows because it gives a false
    # negative due to a metadata mismatch (conda 'vc' vs pip 'msvc-runtime').
    # The 'imports' test above is the reliable indicator of a working package.
    - pip check  # [not win]
  requires:
    - pip
    - python

about:
  home: https://github.com/cnr-isti-vclab/PyMeshLab
  summary: The open source mesh processing python library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
